import streamlit as st
import requests
import os

# Set backend URL cleanly
BACKEND_URL = os.getenv("BACKEND_URL", "https://upsc-ai-backend.onrender.com").rstrip("/")

st.set_page_config(
    page_title="UPSC AI Quest Hub", 
    layout="wide",
    initial_sidebar_state="collapsed"  # Keeps sidebar hidden inside the top-left hamburger menu icon
)

# Initialize active page state
if "active_page" not in st.session_state:
    st.session_state.active_page = "Home"

def navigate_to(page_name):
    st.session_state.active_page = page_name

# --- TOP NAVIGATION BAR (Menu Icon + Home Icon) ---
col_nav1, col_nav2, col_nav3 = st.columns([1, 1, 10])

with col_nav1:
    if st.button("🏠 Home", use_container_width=True):
        navigate_to("Home")

with col_nav2:
    with st.popover("☰ Menu"):
        st.write("**Navigation**")
        if st.button("🏠 Home Overview", use_container_width=True):
            navigate_to("Home")
        if st.button("🎯 Prelims PYQ Quiz", use_container_width=True):
            navigate_to("Prelims PYQ Quiz")
        if st.button("✍️ Mains PYQ Practice", use_container_width=True):
            navigate_to("Mains PYQ Practice")
        if st.button("📊 CSAT PYQ Quiz", use_container_width=True):
            navigate_to("CSAT PYQ Quiz")
        if st.button("⚡ Daily Quiz Generator", use_container_width=True):
            navigate_to("Daily Quiz Generator")
        if st.button("🔍 Universal Mains Evaluator", use_container_width=True):
            navigate_to("Universal Mains Evaluator")

st.markdown("---")

# --- PAGE 1: WELCOME PAGE WITH CLICKABLE FEATURE BUTTONS ---
if st.session_state.active_page == "Home":
    st.title("🚀 UPSC AI Quest Hub")
    st.subheader("Select a tool below to start practicing:")
    st.write("")

    # Row 1
    col1, col2 = st.columns(2)
    
    with col1:
        with st.container(border=True):
            st.subheader("🎯 1. Prelims PYQ Quiz")
            st.write("Custom test maker using official past questions (2006–2025). Filter by subject, topic, and year range with instant automated scoring.")
            if st.button("Launch Prelims Quiz ➔", key="btn_p1", use_container_width=True, type="primary"):
                navigate_to("Prelims PYQ Quiz")
                st.rerun()

    with col2:
        with st.container(border=True):
            st.subheader("✍️ 2. Mains PYQ Answer Writing")
            st.write("Select official Mains questions, write your answer on paper, and upload a photo. The AI scans your handwriting and evaluates your answer like a real UPSC examiner.")
            if st.button("Launch Mains PYQ ➔", key="btn_p2", use_container_width=True, type="primary"):
                navigate_to("Mains PYQ Practice")
                st.rerun()

    st.write("")
    
    # Row 2
    col3, col4 = st.columns(2)

    with col3:
        with st.container(border=True):
            st.subheader("📊 3. CSAT PYQ Practice")
            st.write("Master Math, Logical Reasoning, and Reading Comprehension with dedicated past-year practice sets.")
            if st.button("Launch CSAT Quiz ➔", key="btn_p3", use_container_width=True, type="primary"):
                navigate_to("CSAT PYQ Quiz")
                st.rerun()

    with col4:
        with st.container(border=True):
            st.subheader("⚡ 4. Dynamic Current Affairs & Static Quiz")
            st.write("Generate unlimited practice questions instantly based on recent news and the static UPSC syllabus.")
            if st.button("Launch Dynamic Quiz ➔", key="btn_p4", use_container_width=True, type="primary"):
                navigate_to("Daily Quiz Generator")
                st.rerun()

    st.write("")

    # Row 3
    col5, _ = st.columns([1, 1])
    with col5:
        with st.container(border=True):
            st.subheader("🔍 5. Universal Mains Evaluator")
            st.write("Upload an answer sheet for ANY question—whether generated by our AI or typed/handwritten by you—and receive detailed feedback.")
            if st.button("Launch Universal Evaluator ➔", key="btn_p5", use_container_width=True, type="primary"):
                navigate_to("Universal Mains Evaluator")
                st.rerun()

# --- PAGE 2: PRELIMS PYQ QUIZ ---
elif st.session_state.active_page == "Prelims PYQ Quiz":
    st.title("🎯 Prelims Past Year Question Quiz")
    st.write("Select your criteria below to generate your custom practice test.")

    col1, col2 = st.columns(2)
    with col1:
        subject = st.selectbox("Select Subject", ["Polity & Governance", "Economy", "Modern History", "Environment & Ecology", "Science & Technology", "Geography"])
    with col2:
        years = st.slider("Select Year Range", 2006, 2025, (2015, 2025))

    if st.button("Generate Quiz Test", type="primary"):
        with st.spinner("Fetching questions from database..."):
            try:
                endpoint = f"{BACKEND_URL}/api/v1/pyq/fetch"
                params = {"subject": subject, "year_start": years[0], "year_end": years[1], "exam_type": "Prelims"}
                res = requests.get(endpoint, params=params, timeout=30)
                if res.status_code == 200:
                    data = res.json().get("data", [])
                    if data:
                        st.success(f"Loaded {len(data)} questions!")
                        for idx, q in enumerate(data, 1):
                            st.subheader(f"Question {idx} ({q['year']})")
                            st.write(q["question"])
                            if q.get("options"):
                                st.radio("Select Your Answer:", list(q["options"].items()), format_func=lambda x: f"{x[0]}: {x[1]}", key=f"q_{q['id']}")
                            with st.expander("Show Solution"):
                                st.info(f"Correct Option: {q.get('correct_option', 'N/A')}")
                                st.write(q.get("explanation", ""))
                    else:
                        st.warning("No questions found matching these filters. Try expanding the year range.")
                else:
                    st.error("Server error loading questions.")
            except Exception as e:
                st.error(f"Connection error: {e}")

# --- PAGE 3: MAINS PYQ ANSWER WRITING ---
elif st.session_state.active_page == "Mains PYQ Practice":
    st.title("✍️ Mains PYQ Answer Practice")
    st.write("Pick a subject, get an official question, write your answer on paper, and upload your sheet.")

    subject = st.selectbox("Select Mains Subject", ["GS 1 - History & Society", "GS 2 - Polity & IR", "GS 3 - Economy & Environment", "GS 4 - Ethics"])
    
    if st.button("Get Mains Question"):
        st.info("📌 **Sample Question:** Evaluate the impact of climate change on coastal agriculture in India, suggesting mitigation strategies. (15 Marks, 250 Words)")

    uploaded_file = st.file_uploader("Upload Scanned Answer Sheet (JPG / PNG / PDF)", type=["jpg", "jpeg", "png", "pdf"])
    if uploaded_file and st.button("Evaluate Answer with AI"):
        with st.spinner("AI is reading handwriting (OCR) and evaluating content against UPSC criteria..."):
            st.success("Evaluation Complete!")
            st.markdown("### 📝 Score: **8.5 / 15**")
            st.markdown("**Strengths:** Clear structure, good introduction of IPCC targets.")
            st.markdown("**Areas for Improvement:** Needs map representation of vulnerable coastal regions.")

# --- PAGE 4: CSAT PYQ QUIZ ---
elif st.session_state.active_page == "CSAT PYQ Quiz":
    st.title("📊 CSAT Interactive Arena")
    st.write("Practice Quant, Logical Reasoning, and Reading Comprehension questions.")

    topic = st.selectbox("Select Topic", ["Reading Comprehension", "Data Interpretation", "Logical Reasoning", "Quantitative Aptitude"])
    if st.button("Start CSAT Practice Set"):
        st.info("Loading CSAT question set...")

# --- PAGE 5: DYNAMIC PRELIMS QUIZ ---
elif st.session_state.active_page == "Daily Quiz Generator":
    st.title("⚡ AI Current Affairs & Static Quiz Generator")
    st.write("Fresh questions generated on the spot using the latest UPSC statement-based pattern.")

    cat = st.radio("Quiz Category", ["Current Affairs (Last 12 Months)", "Static Syllabus Mix"])
    if st.button("Generate Fresh Questions"):
        with st.spinner("AI is creating new questions..."):
            st.write("### Sample AI Generated Question")
            st.write("Consider the following statements regarding Central Bank Digital Currency (CBDC):")
            st.write("1. It is a sovereign currency issued by the RBI in digital form.")
            st.write("2. It appears as a liability on the central bank's balance sheet.")
            st.write("Which of the statements given above is/are correct?")
            st.radio("Your Choice:", ["1 only", "2 only", "Both 1 and 2", "Neither 1 nor 2"])

# --- PAGE 6: UNIVERSAL MAINS EVALUATOR ---
elif st.session_state.active_page == "Universal Mains Evaluator":
    st.title("🔍 Universal Mains Answer Evaluator")
    st.write("Evaluate answers for ANY question—whether generated by AI or typed by you.")

    option = st.radio("How would you like to provide the question?", ["Type/Paste the Question", "Question is written on the Answer Sheet"])
    
    if option == "Type/Paste the Question":
        q_text = st.text_area("Enter your question here:")
    
    answer_sheet = st.file_uploader("Upload Scanned Answer Sheet", type=["jpg", "jpeg", "png", "pdf"], key="univ_eval")
    
    if answer_sheet and st.button("Run Comprehensive AI Evaluation"):
        with st.spinner("Analyzing answer structure, facts, and clarity..."):
            st.success("Evaluation Finished!")
            st.markdown("### 📊 Evaluation Summary")
            st.write("**Handwriting Readability:** Excellent")
            st.write("**Relevance to Question:** 80%")
            st.write("**Model Answer Comparison:** Added key constitutional articles missing from user response.")